#!/usr/bin/env python
# -*- coding: utf-8 -*-
""" 
   Created on 15-03-2022
"""
__author__ = "Benedict Wilkins"
__email__ = "benrjw@gmail.com"
__status__ = "Development"

import argparse
from operator import mod
import pathlib

from . import objectify, markdownify
from . import Log

def clean(path): # TODO implement a better clean... this is not very safe
    import shutil
    if pathlib.Path(path).exists():
        shutil.rmtree(path)

parser = argparse.ArgumentParser(prog="mkdocscs", description="")
parser.add_argument("--xml", "-x", type=str, default="./xml", help="Directory contain the .xml files generated by doxygen. Defaults to 'xml' in the calling directory.")
parser.add_argument("--output", "-o", type=str, default="./docs", help="Directory to output .md files. Defaults to 'docs' in the calling directory.")
parser.add_argument("--doxygen", "-d", type=str, default=None, help="Run doxygen using the given config file to generate xml files. The --xml argument will be replaced by doxygen configuration.")
parser.add_argument("--clean", "-c", default=False, action='store_true', help="Clean output directory of old files.")
parser.add_argument("--silent", default=False, action='store_true', help="Suppress warnings and info.")

args = parser.parse_args()
print(args)

xml_dir = pathlib.Path(args.xml).resolve()
xml_dir.mkdir(parents=False, exist_ok=True)
out_dir = pathlib.Path(args.output).resolve()
out_dir.mkdir(parents=False, exist_ok=True)
if not args.clean and next(out_dir.iterdir(), None) is not None:
    Log.warn(f"Output directory {out_dir} is not empty and the '--clean' option wasn't specified, old documentation may remain.")
if args.clean:
    clean(out_dir)

# TODO clean the output dir? maybe do it after generating files?
objects = objectify(str(xml_dir))
markdownify(objects, path=out_dir)

    

